### Check Connection Http API Golang
GET {{baseUrl}}

# Administrator Fitur

## Auth
### Login Administrator
POST {{baseUrl}}/loginAdministrator
Content-Type: application/json
{
    "email : "",
    "password" : "",
}

## Role
### Create Role
POST {{baseUrl}}{{roleUrl}}/createRole
Content-Type: application/json
{
    "role_name" : "Super Administrator",
    "description : "Role untuk mengakses semua fitur"
}
### Get Role
GET {{baseUrl}}/getRole
Content-Type: application/json

### Get Role By Id
GET {{baseUrl}}/getRoleById/123
Content-Type: application/json

### Update Role
PUT {{baseUrl}}/updateRole
### Delete Role
DELETE {{baseUrl}}/deleteRole/123

### Create Administrator
POST {{baseUrl}}/createAdmin
Content-Type: application/json
{
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
}
###

### Create Sekolah

###


# Fitur Students
## Authentication
### Register Students
POST {{baseUrl}}/registerStudents
Content-Type: application/json
{
    "nisn" : "001000300",
    "nama_lengkap" : "",
    "npsn" : "",
    "jenjang_pendidikan" : "",
    "kelas" : "",
    "no_hp" : "",
    "alamat" : "",
    "email" : "",
    "password" : "",
}
### Login Students
POST {{baseUrl}}/loginStudents
Content-Type: application/json
{
    "email" :"dumpstudents",
    "password" :"passwordku123",
}