### Check Connection Http API Golang
GET {{baseUrl}}

# Administrator Fitur

## Role
### Create Role
POST {{baseUrl}}/
### Get Role

### Get Role By Id

### Update Role

### Delete Role

### Create Administrator
POST {{baseUrl}}/createAdmin
###

### Create Sekolah

###


# Fitur Students
## Authentication
### Register Students
POST {{baseUrl}}/registerStudents
Content-Type: application/json
{
    "nisn" : "001000300",
    "nama_lengkap" : "",
    "npsn" : "",
    "jenjang_pendidikan" : "",
    "kelas" : "",
    "no_hp" : "",
    "alamat" : "",
    "email" : "",
    "password" : "",
}
### Login Students
POST {{baseUrl}}/loginStudents
Content-Type: application/json
{
    "email" :"dumpstudents",
    "password" :"passwordku123",
}